apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-deployment
spec:
  selector:
    matchLabels:
      app: pvc-app
  replicas: 1
  template:
    metadata:
      labels:
        app: pvc-app
    spec:
      containers:
      - name: busybox
        image: busybox:1.28
        command: ['sh', '-c', 'mkdir -p /out/ && while true; do echo "$(date) - Test message" >> /out/output.txt; sleep 5; done']
        volumeMounts:
        - name: volume
          mountPath: /out
      - name: multitool
        image: wbitt/network-multitool
        command: ['sh', '-c', 'tail -f /out/output.txt']
        volumeMounts:
        - name: volume
          mountPath: /out
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: pvc-volume